# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
np.__version__

'1.24.4'

In [3]:
np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BL

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [4]:
# a = np.random.rand(2, 3, 5)
a = np.random.random((2,3,5))


### 4. Print a.


In [5]:
a

array([[[0.7876309 , 0.58625562, 0.11670891, 0.63880881, 0.78874415],
        [0.46695047, 0.09601872, 0.84033469, 0.88726176, 0.10562818],
        [0.06752735, 0.57507193, 0.39118953, 0.26461573, 0.24300379]],

       [[0.58639376, 0.19097637, 0.63695705, 0.82543976, 0.8749271 ],
        [0.06428118, 0.06096681, 0.29987612, 0.83118993, 0.64619216],
        [0.0219458 , 0.25629004, 0.37182517, 0.13425789, 0.05776747]]])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [6]:
b = np.ones((5,3,2))


### 6. Print b.


In [7]:
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [8]:
print("Size of a = ",a.size)
print("Size of b = ",b.size)
print("Do a and b have the same size ?", a.size == b.size)

Size of a =  30
Size of b =  30
Do a and b have the same size ? True



### 8. Are you able to add a and b? Why or why not?


In [9]:
#No, because they have different shape



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [10]:
c = b.T
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [11]:
d = a + c
d

array([[[1.7876309 , 1.58625562, 1.11670891, 1.63880881, 1.78874415],
        [1.46695047, 1.09601872, 1.84033469, 1.88726176, 1.10562818],
        [1.06752735, 1.57507193, 1.39118953, 1.26461573, 1.24300379]],

       [[1.58639376, 1.19097637, 1.63695705, 1.82543976, 1.8749271 ],
        [1.06428118, 1.06096681, 1.29987612, 1.83118993, 1.64619216],
        [1.0219458 , 1.25629004, 1.37182517, 1.13425789, 1.05776747]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [12]:
print(a)
print('\n\n')
print(d)

[[[0.7876309  0.58625562 0.11670891 0.63880881 0.78874415]
  [0.46695047 0.09601872 0.84033469 0.88726176 0.10562818]
  [0.06752735 0.57507193 0.39118953 0.26461573 0.24300379]]

 [[0.58639376 0.19097637 0.63695705 0.82543976 0.8749271 ]
  [0.06428118 0.06096681 0.29987612 0.83118993 0.64619216]
  [0.0219458  0.25629004 0.37182517 0.13425789 0.05776747]]]



[[[1.7876309  1.58625562 1.11670891 1.63880881 1.78874415]
  [1.46695047 1.09601872 1.84033469 1.88726176 1.10562818]
  [1.06752735 1.57507193 1.39118953 1.26461573 1.24300379]]

 [[1.58639376 1.19097637 1.63695705 1.82543976 1.8749271 ]
  [1.06428118 1.06096681 1.29987612 1.83118993 1.64619216]
  [1.0219458  1.25629004 1.37182517 1.13425789 1.05776747]]]



### 12. Multiply a and c. Assign the result to e.


In [13]:
e = a * c
e

array([[[0.7876309 , 0.58625562, 0.11670891, 0.63880881, 0.78874415],
        [0.46695047, 0.09601872, 0.84033469, 0.88726176, 0.10562818],
        [0.06752735, 0.57507193, 0.39118953, 0.26461573, 0.24300379]],

       [[0.58639376, 0.19097637, 0.63695705, 0.82543976, 0.8749271 ],
        [0.06428118, 0.06096681, 0.29987612, 0.83118993, 0.64619216],
        [0.0219458 , 0.25629004, 0.37182517, 0.13425789, 0.05776747]]])



### 13. Does e equal to a? Why or why not?


In [14]:
print("Does e equal a?", np.array_equal(e, a))
# Because e is the product of a * c and c is an array of ones

Does e equal a? True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [15]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print("d_max:", d_max, "\n", "d_min:", d_min, "\n","d_mean:", d_mean)

d_max: 1.8872617638216642 
 d_min: 1.0219458000139654 
 d_mean: 1.4238345713233047



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [16]:
#f = np.empty_like(d)
f = np.empty((2,3,5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



if d.max() > x > d.mean():
    f[x,y,z] = 75
elif value == d.mean():
    f[x,y,z] = 50
elif value == d.min():
    f[x,y,z] = 0
elif value == d.max():
    f[x,y,z] = 100
elif d.min() < value < d.mean():
    f[x,y,z] = 50

In [17]:
print("d_max:", d_max, "\n", "d_min:", d_min, "\n","d_mean:", d_mean)

d_max: 1.8872617638216642 
 d_min: 1.0219458000139654 
 d_mean: 1.4238345713233047


In [18]:
d

array([[[1.7876309 , 1.58625562, 1.11670891, 1.63880881, 1.78874415],
        [1.46695047, 1.09601872, 1.84033469, 1.88726176, 1.10562818],
        [1.06752735, 1.57507193, 1.39118953, 1.26461573, 1.24300379]],

       [[1.58639376, 1.19097637, 1.63695705, 1.82543976, 1.8749271 ],
        [1.06428118, 1.06096681, 1.29987612, 1.83118993, 1.64619216],
        [1.0219458 , 1.25629004, 1.37182517, 1.13425789, 1.05776747]]])

In [19]:
d.shape

(2, 3, 5)

In [20]:
for x in range(2):
    for y in range(3):
        for z in range(5):
            value = d[x,y,z]
            if d.max() > value > d.mean():
                f[x,y,z] = 75
            elif value == d.mean():
                f[x,y,z] = 50
            elif value == d.min():
                f[x,y,z] = 0
            elif value == d.max():
                f[x,y,z] = 100
            elif d.min() < value < d.mean():
                f[x,y,z] = 25
f            

array([[[ 75.,  75.,  25.,  75.,  75.],
        [ 75.,  25.,  75., 100.,  25.],
        [ 25.,  75.,  25.,  25.,  25.]],

       [[ 75.,  25.,  75.,  75.,  75.],
        [ 25.,  25.,  25.,  75.,  75.],
        [  0.,  25.,  25.,  25.,  25.]]])





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [21]:
print(d)
print("\n")
print(f)

[[[1.7876309  1.58625562 1.11670891 1.63880881 1.78874415]
  [1.46695047 1.09601872 1.84033469 1.88726176 1.10562818]
  [1.06752735 1.57507193 1.39118953 1.26461573 1.24300379]]

 [[1.58639376 1.19097637 1.63695705 1.82543976 1.8749271 ]
  [1.06428118 1.06096681 1.29987612 1.83118993 1.64619216]
  [1.0219458  1.25629004 1.37182517 1.13425789 1.05776747]]]


[[[ 75.  75.  25.  75.  75.]
  [ 75.  25.  75. 100.  25.]
  [ 25.  75.  25.  25.  25.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  25.  25.  75.  75.]
  [  0.  25.  25.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [27]:
f_2 = np.empty((2,3,5), dtype = 'object')
f_2

array([[[None, None, None, None, None],
        [None, None, None, None, None],
        [None, None, None, None, None]],

       [[None, None, None, None, None],
        [None, None, None, None, None],
        [None, None, None, None, None]]], dtype=object)

In [28]:
for x in range(2):
    for y in range(3):
        for z in range(5):
            value = d[x,y,z]
            if d.max() > value > d.mean():
                f_2[x,y,z] = "D"
            elif value == d.mean():
                f_2[x,y,z] = "C"
            elif value == d.min():
                f_2[x,y,z] = "A"
            elif value == d.max():
                f_2[x,y,z] = "E"
            elif d.min() < value < d.mean():
                f_2[x,y,z] = "B"
f_2            

array([[['D', 'D', 'B', 'D', 'D'],
        ['D', 'B', 'D', 'E', 'B'],
        ['B', 'D', 'B', 'B', 'B']],

       [['D', 'B', 'D', 'D', 'D'],
        ['B', 'B', 'B', 'D', 'D'],
        ['A', 'B', 'B', 'B', 'B']]], dtype=object)